### ISSUE TITLE
Functions undefined 

### ISSUE THREAD

**Issue by Michky** [itssimple/overwolf-get-supported-features#2]
Hello,

When i try to use your examples in node js, the response with the methods is undefined 

![imagen](https://user-images.githubusercontent.com/18129391/99345922-6e283680-2861-11eb-89f6-a7632ff7c27c.png)

How can i fix it ?

Best regards

**Comment by itssimple** [comment]
Hey! Thanks for using my package. It seems that I forgot to write documentation on how to use it outside of Overwolf! ^^

This has been fixed in 1.8.3!

And you can use it like this

```js
const fetch = require('node-fetch');
global.fetch = fetch;
let { 
    getSupportedFeatures, 
    getSupportedFeaturesOnline, 
    OverwolfGameWithEventSupport 
} = require("overwolf-games-features");

let supportedFeatures = getSupportedFeatures(OverwolfGameWithEventSupport.Overwatch);

console.log('Local features', supportedFeatures);

getSupportedFeaturesOnline(OverwolfGameWithEventSupport.Overwatch, features => {
    console.log('Online features', features);
});
```

https://runkit.com/itssimple/5fb36653c6787c001a7a7ba2
